title: Shell-Cell Documentation
description: A simple guide for Shell-Cell.
remote_theme: just-the-docs/just-the-docs

# This tells Jekyll to use the theme you want
theme: just-the-docs

# URL settings (GitHub Pages specific)
# Replace 'username' and 'repo-name' with yours
url: "https://username.github.io"
baseurl: "/repo-name" 

aux_links:
  "GitHub Repo": "https://github.com/Mr-Leshiy/shell-cell"